export const DECREASE_TIME = "DECREASE_TIME";
export const RESET_TIME = "RESET_TIME";
export const UPDATE_NUMBER_OF_STARS = "UPDATE_NUMBER_OF_STARS";
export const UPDATE_AVAILABLE_NUMBERS = "UPDATE_AVAILABLE_NUMBERS";
export const UPDATE_CANDIDATE_NUMBERS = "UPDATE_CANDIDATE_NUMBERS";