export const sections = [
    {
        id: "section-1",
        title: "Section 1",
        content:
            "Cras eleifend odio a metus fermentum pharetra. Ut eu ultricies magna. Vivamus facilisis, libero at molestie condimentum, eros sapien malesuada mauris, ac viverra purus nulla nec dolor. Curabitur lobortis felis vitae tellus interdum, ultricies volutpat lacus dictum. Nunc porta, arcu sit amet luctus viverra, nulla magna pharetra ipsum, et finibus enim felis id nulla. Pellentesque ultrices, metus at placerat sagittis, diam augue sollicitudin nisl, quis dictum quam nulla id justo. Phasellus finibus, eros quis mollis sollicitudin, lorem metus ultrices nunc, sed egestas risus risus eget nisl. Duis at leo rutrum, dapibus orci luctus, consectetur ligula. Ut cursus, justo sed pharetra malesuada, sapien risus fermentum massa, bibendum mollis nulla purus sed mi.\n" +
            "Integer ac diam at urna accumsan congue. Morbi volutpat elit nunc, et aliquam elit vulputate ut. Mauris ut orci luctus, tincidunt augue eu, semper arcu. Nunc condimentum, nisi non malesuada aliquet, ante tellus commodo ipsum, nec accumsan ligula nibh et est. Nulla facilisi. Curabitur velit dui, lacinia in mollis sed, venenatis quis eros. Aenean commodo nunc a justo euismod tincidunt. Mauris hendrerit, nunc et commodo tincidunt, metus velit feugiat quam, ac egestas felis felis eu augue.\n" +
            "Nunc vestibulum volutpat tincidunt. In quis finibus ligula. Fusce feugiat turpis non hendrerit varius. Suspendisse non eros felis. Praesent varius pellentesque finibus. Praesent eu diam tellus. Integer vitae mauris eu turpis tincidunt facilisis. Ut id lorem luctus, tincidunt eros ut, congue est. Integer lobortis vestibulum commodo. Nulla et pellentesque augue. Sed dapibus urna eu turpis auctor pretium. Maecenas sed massa lorem. Etiam mollis augue vel lorem feugiat, nec vestibulum dolor dapibus. Praesent velit dui, tempor a blandit eget, euismod vel velit.\n" +
            "Fusce viverra iaculis arcu, non ultricies risus rutrum ut. Suspendisse potenti. Vivamus libero mi, faucibus eu lectus id, convallis tristique purus. Sed eu congue quam. Fusce ac dapibus dolor. Fusce varius volutpat orci, nec porta lectus imperdiet sit amet. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam nunc felis, bibendum at neque sed, sollicitudin rhoncus massa. Maecenas placerat fermentum semper. In hac habitasse platea dictumst. Aenean semper risus sed enim sodales varius at vitae lorem.\n" +
            "Pellentesque tincidunt quam vel nulla malesuada imperdiet. Curabitur ut dui magna. Morbi volutpat arcu vitae luctus pellentesque. Proin dapibus, est nec ornare suscipit, sem metus auctor metus, in pellentesque felis leo id erat. Sed non ornare dui. Sed ut vehicula augue, vitae imperdiet nibh. Aliquam nec placerat mi. Sed blandit porttitor orci id tristique. Praesent luctus, odio sit amet consectetur euismod, mauris tortor convallis nunc, a dapibus augue neque id est. ",
        imageName: "new_game_screen.png"
    }, {
        id: "section-2",
        title: "Section 2",
        content:
            "Nunc molestie, nibh a laoreet venenatis, justo tortor pretium purus, a fringilla massa felis sit amet purus. Donec rutrum, turpis non tincidunt aliquam, turpis leo posuere dui, at congue lorem orci quis ex. Nullam porttitor leo auctor urna volutpat venenatis. Ut feugiat nulla eu ipsum pellentesque efficitur. Cras at eros a tellus elementum viverra. Nunc lobortis lectus nec dui faucibus, a imperdiet ligula suscipit. Mauris et imperdiet metus. Vivamus mollis arcu a nisi congue, a tincidunt nibh placerat. Suspendisse potenti. Praesent placerat mi condimentum fermentum sodales. Aenean aliquam non dolor tristique pellentesque. Pellentesque porta sodales tristique. Vivamus id tincidunt neque, ut vestibulum lacus. Etiam et urna tortor.\n" +
            "Proin porta justo libero, a maximus elit egestas sit amet. Nullam vel orci eget neque bibendum laoreet. Morbi eget enim faucibus, porta dui eget, pulvinar nunc. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vestibulum efficitur orci sit amet aliquet egestas. Praesent eget nulla sit amet libero blandit suscipit. Curabitur sit amet faucibus ipsum, non eleifend nisl. Nunc ultricies scelerisque tellus et tincidunt. Mauris varius massa ut velit tempus, ut mattis nulla porta. Vestibulum eu fermentum dui. Morbi faucibus eleifend egestas. Fusce in neque ex. Sed euismod dignissim dui sed gravida. Vestibulum malesuada congue magna, id faucibus magna bibendum non. Quisque vestibulum, elit finibus sagittis congue, purus sapien congue diam, vitae porttitor tortor tellus malesuada urna.\n" +
            "Cras sit amet est vel purus sagittis ullamcorper non laoreet libero. Proin non dui iaculis, pellentesque nulla sed, tristique nisl. Praesent vulputate, lacus sed tincidunt accumsan, nunc ex pharetra diam, ac ultricies justo sapien ac massa. Aenean id erat eget felis ultricies dignissim at at enim. Donec efficitur ligula maximus, volutpat augue cursus, euismod nulla. Praesent venenatis, magna non pharetra finibus, turpis risus ullamcorper sapien, nec facilisis massa odio maximus sapien. Etiam aliquet nisi sed magna tempus malesuada. Integer at odio a massa sagittis fringilla. Nunc pulvinar mauris vitae turpis fermentum pharetra dignissim in sapien. Donec ultricies ullamcorper tellus ac imperdiet.\n" +
            "Morbi dignissim consectetur felis ac hendrerit. Ut in libero nisi. Pellentesque eget nunc imperdiet orci consectetur auctor at et dolor. Aenean et consequat massa. Praesent dictum pulvinar leo, ac lobortis metus maximus eu. Suspendisse congue eros non dolor pretium, non consectetur libero accumsan. Nulla laoreet velit nibh, id interdum augue cursus eget. Curabitur mattis imperdiet sollicitudin. Suspendisse potenti. Fusce consequat risus sed augue euismod euismod vestibulum in nunc.\n" +
            "Sed magna justo, porttitor at venenatis sit amet, consequat vel tellus. Fusce sed massa eget velit pulvinar lobortis a pellentesque felis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Proin in quam vitae orci congue elementum. Nunc eget rhoncus nibh. Nunc ac mollis lectus, porta aliquet sem. Morbi consectetur euismod faucibus. In et diam mauris. ",
        imageName: "candidates_screen.png"
    }, {
        id: "section-3",
        title: "Section 3",
        content:
            "Phasellus dui sapien, accumsan at diam in, laoreet volutpat erat. Maecenas ornare, lacus eu porttitor sollicitudin, odio diam ullamcorper purus, a pharetra mi metus ac ex. Aenean justo nunc, pellentesque ultricies bibendum sed, feugiat ac lorem. Fusce fringilla pellentesque rutrum. Praesent auctor dapibus eros posuere condimentum. Vestibulum auctor dapibus neque et molestie. Sed sed volutpat magna. Vestibulum maximus eleifend ex, non convallis dolor laoreet eget. Nunc commodo ornare feugiat. Phasellus pretium consequat sollicitudin.\n" +
            "Sed ut posuere tellus, in tincidunt nibh. Morbi id augue neque. Quisque pulvinar mi non neque tristique hendrerit. Fusce et faucibus lectus. Morbi eu vestibulum libero. Sed eu orci accumsan, accumsan justo sed, egestas risus. Mauris euismod est vel dui dapibus accumsan. Integer quis est a neque cursus fermentum et sodales sem. Aenean vitae libero ut lorem finibus efficitur et at felis. Praesent nulla nibh, vulputate non metus ultricies, iaculis ultricies augue. Ut congue pulvinar metus nec pellentesque. Nam vel ligula neque.\n" +
            "Ut vel mauris feugiat, pharetra justo et, dictum eros. Suspendisse convallis condimentum eros, a accumsan arcu. Maecenas lectus mauris, varius id neque sit amet, lacinia commodo mauris. In molestie, orci id fringilla commodo, ex risus bibendum augue, eget dictum turpis metus eu elit. Aliquam molestie varius imperdiet. Nam vel lacus eget lectus aliquam accumsan at sit amet ligula. Proin dolor tellus, dictum a consectetur sed, placerat ac urna. In hac habitasse platea dictumst. Donec nunc ipsum, dapibus at vulputate sed, hendrerit vitae nulla. Cras eget magna euismod, tincidunt mi nec, gravida enim.\n" +
            "Donec hendrerit sagittis magna, vitae rhoncus sapien venenatis id. Praesent euismod, neque sit amet finibus dictum, urna dui rhoncus massa, eget sodales sem ante vel massa. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque vel lacinia diam. Sed pulvinar molestie dolor. Morbi dignissim vehicula mauris, a ornare est sagittis sed. Fusce a tincidunt purus. Vestibulum convallis augue eget suscipit cursus. Aliquam erat volutpat. Nulla id felis urna. Etiam nisi sapien, hendrerit in tortor quis, malesuada lobortis quam. Donec consectetur posuere nisi vitae mollis. Proin eget aliquam ipsum, eu tempor lacus. Curabitur id vestibulum turpis. Praesent a quam et ligula accumsan elementum. Fusce commodo volutpat est, eu tincidunt enim posuere sed.\n" +
            "Sed sodales consequat tortor, convallis facilisis dolor pulvinar vulputate. Pellentesque quis vehicula tortor, non dictum lorem. In bibendum at nunc at placerat. Etiam egestas massa non arcu ultricies cursus. Cras mollis, nisl ut fermentum semper, nunc sem pretium justo, in sollicitudin augue ante a ante. Pellentesque non diam in quam tincidunt tincidunt quis id nibh. Donec faucibus vitae risus a posuere. Maecenas tristique tortor et metus aliquet dictum. "
    }, {
        id: "section-4",
        title: "Section 4",
        content: "Suspendisse tincidunt in mauris ut tristique. Nam posuere ut quam non tempor. Aliquam rhoncus viverra nibh non vehicula. Pellentesque commodo pulvinar sem ac dapibus. Integer vel eros felis. Sed et quam turpis. Vestibulum ac nibh in nisi placerat molestie. Nulla tempor pulvinar ipsum ut volutpat. Nam luctus ornare vulputate. Vestibulum ultricies commodo est.\n" +
            "Ut quis ullamcorper purus. Etiam nec dolor semper dolor tincidunt lacinia. Aliquam consectetur ligula vestibulum suscipit sagittis. Mauris a tristique libero. Quisque vel urna sollicitudin, sodales augue at, tempus mi. Vivamus nibh lacus, blandit nec magna eu, iaculis mollis lorem. Mauris tempor lectus eget enim tincidunt bibendum. Pellentesque congue, libero semper commodo aliquam, velit urna feugiat justo, vitae rutrum lorem tortor ac sem. Suspendisse nec dignissim lacus. Phasellus vulputate risus sit amet nisi porttitor, rhoncus imperdiet ante ullamcorper. Vestibulum egestas laoreet efficitur. Duis sollicitudin urna a neque dictum pulvinar. Nullam et fermentum mauris, ut sollicitudin leo. Duis sagittis, elit ut tempor gravida, augue metus fringilla nisi, eget commodo purus ante sit amet augue.\n" +
            "Duis lobortis ultricies massa id viverra. Donec consectetur justo eu molestie rhoncus. Donec a metus mi. Nullam vitae ipsum sed felis ornare interdum. Vestibulum faucibus ultricies nisl, quis malesuada metus dignissim at. Etiam eu tempus velit, at venenatis dolor. Curabitur mollis dui eget erat tincidunt, eget pulvinar leo placerat. Praesent nec quam ornare ante vestibulum pharetra. Vivamus convallis libero sit amet sapien vehicula placerat. Aenean pharetra nisl eget odio faucibus porttitor. Aenean pellentesque ante eget arcu finibus, a fringilla turpis euismod.\n" +
            "Etiam feugiat, lorem vel sagittis tempor, turpis ligula semper ex, ac sodales mi arcu ut quam. Nunc semper nibh at gravida tristique. Ut mattis dignissim nisl quis imperdiet. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aliquam nunc enim, rhoncus vel elementum eget, bibendum et sem. Vivamus laoreet neque ac lectus fringilla, quis sagittis justo imperdiet. Phasellus pretium maximus massa, non varius odio convallis quis. In sit amet auctor mauris. Praesent quam ex, lacinia a rhoncus a, sollicitudin quis nibh.\n" +
            "Quisque eu condimentum leo, a rhoncus velit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Maecenas fringilla leo hendrerit tellus porta imperdiet. Ut eleifend nulla quam, placerat rutrum enim scelerisque at. Nunc at vulputate odio. Suspendisse potenti. Nullam accumsan rhoncus sem, sed egestas leo faucibus id. Aliquam vitae aliquet felis. ",
        imageName: "loser_screen.png"
    }, {
        id: "section-5",
        title: "Section 5",
        content: "Nullam sit amet neque nunc. Morbi convallis vel nibh ut bibendum. Cras pellentesque enim nisl, quis maximus ex placerat id. Nulla semper urna dui, a tempus ex tempor nec. Nunc vehicula erat ante, quis egestas dolor congue quis. Sed porttitor, magna non tristique mattis, eros nisl dictum purus, eu maximus libero lectus et mi. Sed nulla nisl, facilisis nec mollis at, sodales non velit. Lorem ipsum dolor sit amet, consectetur adipiscing elit.\n" +
            "Cras quis gravida dolor, ullamcorper facilisis velit. Donec malesuada leo sit amet lorem interdum dapibus. Praesent nisi ex, facilisis a suscipit sagittis, sollicitudin ut erat. Donec suscipit ipsum a vestibulum faucibus. Integer sollicitudin, lacus vitae convallis convallis, quam urna ullamcorper velit, at fermentum urna massa lobortis arcu. Aliquam vel ligula at dui eleifend vulputate nec vitae risus. Donec ornare, risus id commodo volutpat, neque mi auctor metus, sit amet hendrerit velit erat ac magna. Fusce venenatis, lacus in maximus faucibus, mi nisi elementum ipsum, ac egestas tortor massa ut magna. Cras iaculis, orci a rhoncus tempus, nulla est lacinia diam, vel feugiat libero ipsum eu enim.\n" +
            "Nullam laoreet odio nec eros placerat congue. Curabitur interdum vel lectus ut vehicula. Ut arcu nibh, ornare eget euismod volutpat, porta id sapien. Mauris ante risus, rhoncus eget aliquam sit amet, pharetra eu metus. Nam consectetur massa et sapien ullamcorper, vel iaculis elit efficitur. Vestibulum id velit ante. Donec ac tempor felis, eget volutpat nibh. Donec viverra dolor lectus, id vestibulum neque blandit id. Vestibulum feugiat justo at sapien condimentum, quis rhoncus velit accumsan. Nullam placerat scelerisque nisi ac laoreet. Vestibulum suscipit, diam nec pretium hendrerit, lorem arcu vestibulum turpis, sed accumsan dui nisl ut massa.\n" +
            "Proin faucibus ante sit amet orci dapibus, a consectetur massa congue. Aliquam ut diam arcu. Aliquam facilisis tellus semper, consectetur ipsum in, aliquet mi. Ut auctor quam vitae lacus aliquet, sit amet sodales tellus vestibulum. Quisque feugiat sagittis ultrices. Sed scelerisque pellentesque laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Mauris malesuada mattis massa at porttitor.\n" +
            "Vivamus dignissim, dui id elementum finibus, turpis augue rhoncus quam, eget pharetra dolor magna vitae arcu. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Fusce lacinia purus pellentesque risus volutpat, in tempor mi porta. Quisque sollicitudin dui risus. Nunc euismod condimentum eros, id luctus felis tempus at. Vivamus vehicula libero nulla, non iaculis tortor congue a. Nam aliquet gravida malesuada. Maecenas et fringilla neque. ",
        imageName: "winner_screen.png"
    }
]